### ISSUE TITLE
inconsistent messages when search query is running

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/domain_discovery_API#13]
![image](https://cloud.githubusercontent.com/assets/2118982/26615982/403f27fa-4599-11e7-8a1f-e4bb68393cf1.png)

**Comment by julianafreire** [comment]
The query is still running and in the Snippets view there is a message saying "No pages found"

(I ran the query on Bing after trying on Google. There seems to be a problem with the state of the app when we move from one query to the next. In this case, I think that the natural behavior would be to reset all filters when a query is run; i.e., if I issue a Bing query, all results from bing should be displayed.)

**Comment by soniacq** [comment]
1. Fixed inconsistent message when search query is running. Now, if the search query is running we show 'searching...' instead of 'No pages found'.
2. Fixed issue related with search query. Now, we reset all filters when a query is run.
