### ISSUE TITLE
can't query (potential problem with multi-term queries)

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/domain_discovery_API#14]
Search queries sometimes do not work. I tried "hanan samet". It did not work.
I restarted the server (did control-C and ran the script again), and it still did not work.

Is this an issue parsing multi-term queries?

See a piece of the log below

 MULTIFIELD TERM SEARCH 
{'filter': {'or': [{'term': {'query': u'"hanan samet"'}}]}, 'query': {'bool': {'minimum_number_should_match': 0, 'should': []}}, 'fields': ['url', 'description', 'image_url', 'title', 'rank', 'x', 'y', 'tag', 'retrieved']} 

172.17.0.1 - - [31/May/2017:04:46:05] "POST /getPages HTTP/1.1" 200 37 "http://localhost:8084/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

{'filter': {'or': [{'term': {'query': u'"hanan samet"'}}]}} 

 MULTIFIELD TERM SEARCH 
{'filter': {'or': [{'term': {'query': u'"hanan samet"'}}]}, 'query': {'bool': {'minimum_number_should_match': 0, 'should': []}}, 'fields': ['url', 'description', 'image_url', 'title', 'rank', 'x', 'y', 'tag', 'retrieved']}

**Comment by julianafreire** [comment]
Other queries that do not work: grid spatial index (see log below), grid index
Strangely enough, the following query works: juliana freire

Why is it that some queries work and some don't?

 MULTIFIELD TERM SEARCH 
{'filter': {'or': [{'term': {'query': u'grid spatial index'}}]}, 'query': {'bool': {'minimum_number_should_match': 0, 'should': []}}, 'fields': ['url', 'description', 'image_url', 'title', 'rank', 'x', 'y', 'tag', 'retrieved']} 



172.17.0.1 - - [31/May/2017:05:25:36] "POST /getPages HTTP/1.1" 200 37 "http://localhost:8084/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"



 QUERY WEB OUTPUT 




 downloaderService terminated 



Number of results: 0







 QUERY WEB ERRORS 
None 



172.17.0.1 - - [31/May/2017:05:25:36] "POST /queryWeb HTTP/1.1" 200 25 "http://localhost:8084/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"



{'filter': {'or': [{'term': {'query': u'grid spatial index'}}]}} 






 MULTIFIELD TERM SEARCH 
{'filter': {'or': [{'term': {'query': u'grid spatial index'}}]}, 'query': {'bool': {'minimum_number_should_match': 0, 'should': []}}, 'fields': ['url', 'description', 'image_url', 'title', 'rank', 'x', 'y', 'tag', 'retrieved']} 



172.17.0.1 - - [31/May/2017:05:25:36] "POST /getPages HTTP/1.1" 200 37 "http://localhost:8084/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"

**Comment by yamsgithub** [comment]
Both the queries were tested and are working.
