### ISSUE TITLE
search bug: two concurrent searches --> can't get rid of search query

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/domain_discovery_API#17]
I used the newest version to test a query that did not work before:
hanan samet

Having the message "searching" is great -- it is now clear the system is working.
But this particular query took too long, so I modified it to
hanan

Then DDT kept swapping from hanan to "hanan samet". After a while it stopped 'blinking' and said "Query failed. Try Google"

At this point, I wanted to check the results for the hanan query. But when I clicked on the X to remove the query "hanan samet", the interface shows the search results, and then immediately goes back to the empty screen. 

![image](https://user-images.githubusercontent.com/2118982/26996440-46505020-4d40-11e7-8cb4-08a1ec89fa34.png)

**Comment by yamsgithub** [comment]
Fixed.
