### ISSUE TITLE
Search results: Cannot click on URL

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/domain_discovery_API#8]
It seems that pages without a title cannot be 'clicked on'. See geotrellis.io in screenshot

![cannot-click](https://cloud.githubusercontent.com/assets/2118982/26615465/f8aa8a32-4594-11e7-9b24-5c9d33ac7139.png)

**Comment by soniacq** [comment]
Fixed. Now we are creating a title to untitled pages. In this way user can access all pages from DDT.
