### ISSUE TITLE
Need to access crawler labels

### ISSUE THREAD

**Issue by julianafreire** [ViDA-NYU/domain_discovery_API#9]
The labels assigned by the crawler need to be visible in DDT.
Can they be added as "Model Tags"?

**Comment by julianafreire** [comment]
Yamuna wrote:"Shouldn't this be done on the ache monitor? The classifier used for model tags is different from ache classifier. So the results would be confusing?"

I disagree. As is, we lose the crawler labels and are unable to filter the relevant pages.
If we label using the ACHE monitor, we don't get any improvements on the model. 

As for the classifiers being different, since they use the same positive and negative examples, they should be 'similar'. 

I suggest we import the labels for now.

After the deadline, we can consider allowing the user to swap the online classifier for the static classifier used by ACHE.

**Comment by yamsgithub** [comment]
You are right. We should show the relevant and irrelvant pages in the
crawled data separately so the user can see how the crawler is performing
which is the point of integrating the crawled data into DDT.

I have now created a separate facet called "Crawled Data". Under that I
show the pages labeled Relevant and Irrelevant by the ache model.

Attached is the screen shot with the change:

Thanks
Yamuna
